# Generated by Django 5.0.2 on 2024-03-06 20:56

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='media/', validators=[core.validators.file_size], verbose_name='Файл')),
                ('obj', models.CharField(choices=[(1, 'Leomall'), (2, 'Калейдоскоп'), (3, 'Сан сити'), (4, 'Столица')], default='Калейдоскоп', max_length=25, verbose_name='Объект')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
