# Generated by Django 5.0.2 on 2024-03-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='name',
            field=models.CharField(default='', max_length=225),
        ),
    ]
