# Generated by Django 5.0.2 on 2024-03-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_uploadmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='name',
            field=models.CharField(default='jopa', max_length=225, primary_key=True, serialize=False),
        ),
    ]
